### ISSUE TITLE
Add `BoundQuerier` use to contract macro

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/sylvia#205] opened 2023-07-26 10:51 UTC
Since sylvia 0.5.0 it's necessary to add

`use crate::contract::BoundQuerier;`

before using the `#[contract]` macro.

Either document this, or include the use directive directly in the macro (or directly qualify the `BoundQuerier` usage).

**Comment by hashedone** [comment] 2023-07-31 09:57
@jawoznia we should address it

**Comment by jawoznia** [comment] 2023-07-31 12:36
The issue appears when implementing interface on contract.
Currently if `impl Interface for Contract` is in different module than `Contract` itself you need to provide path to the contract file via f.e. `#[contract(module=crate::contract)`. It is described in `Macro attributes` section in `README`.

I will add info in the troubleshooting section and think about better explanation in whole `README`

**Comment by hashedone** [comment] 2024-02-20 13:32
Dupe of #164

**Closed by hashedone** 2024-02-20 13:32 UTC
